esphome:
  name: projecteur-tuya
  friendly_name: projecteur-tuya
  on_boot:
    priority: -100
    then:
      - light.control:
          id: projecteur_tuya
          effect: ddp

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api
ota:
  password: !secret ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Projecteur Fallback Hotspot"
    password: !secret wifi_fallback
captive_portal:

web_server:
  port: 8888

binary_sensor:
  # Reports if this device is Connected or not
  - platform: status
    name: ${friendly_name} Status

sensor:
  # Reports the WiFi signal strength
  - platform: wifi_signal
    name: ${friendly_name} Signal
    update_interval: 60s

  # Reports how long the device has been powered (in minutes)
  - platform: uptime
    name: ${friendly_name} Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes

external_components:
  - source:
      type: git
      url: https://github.com/KaufHA/common
    components: [ ddp ]
    refresh: always

ddp:

light:
  - platform: rgbww
    name: "Projecteur Tuya"
    id: projecteur_tuya
    red: pwm_output_r
    green: pwm_output_g
    blue: pwm_output_b
    cold_white: pwm_output_cw
    warm_white: pwm_output_ww
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K
    color_interlock: true
    restore_mode: ALWAYS_ON
    effects:
      - ddp
      - random:
      - strobe:

output:
  - platform: libretiny_pwm
    pin: P24
    frequency: 1000 Hz
    id: pwm_output_ww
  - platform: libretiny_pwm
    pin: P26
    frequency: 1000 Hz
    id: pwm_output_cw
  - platform: libretiny_pwm
    pin: P8
    frequency: 1000 Hz
    id: pwm_output_r
  - platform: libretiny_pwm
    pin: P7
    frequency: 1000 Hz
    id: pwm_output_g
  - platform: libretiny_pwm
    pin: P6
    frequency: 1000 Hz
    id: pwm_output_b
